// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MDIS.api.Data;
using System;
using System.Collections.Generic;

namespace MDIS.api.Model
{
    public partial class TbDrone
    {
        public TbDrone()
        {
            TbFlying = new HashSet<TbFlying>();
        }

        public string DroneMid { get; set; }
        public string DroneId { get; set; }
        public string DroneType { get; set; }
        public string IdType { get; set; }
        public string Isauth { get; set; }
        public string Isvalid { get; set; }
        public string Isfaultflying { get; set; }
        public string Isuse { get; set; }
        public string StatusCode { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Altitude { get; set; }
        public string HeightType { get; set; }
        public double Speed { get; set; }
        public double Direction { get; set; }
        public string Postno { get; set; }
        public double LatitudeOpen { get; set; }
        public double LongitudeOpen { get; set; }
        public double AltitudeOpen { get; set; }
        public string PostnoOpen { get; set; }
        public DateTime UpdateTime { get; set; }
        public DateTime CreateTime { get; set; }

        public virtual ICollection<TbFlying> TbFlying { get; set; }
    }
}