// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MDIS.api.Model
{
    public partial class TbFlying
    {
        public string FlyingId { get; set; }
        public string DroneId { get; set; }
        public float AvgSpeed { get; set; }
        public float FlyingDistance { get; set; }
        public float FlyingTime { get; set; }
        public DateTime FlyingStartTime { get; set; }
        public DateTime FlyingEndTime { get; set; }
        public string Postno { get; set; }
        public string CmPostno { get; set; }
        public float ControlDistance { get; set; }

        public virtual TbDrone Drone { get; set; }
    }
}